databases:
  LARIAT_SNOWFLAKE_TEST:
    PUBLIC:
    - BANK_ACCOUNTS
  LARIAT_SNOWFLAKE_TEST_2:
    PUBLIC_2:
    - BANK_ACCOUNTS_2
  LARIAT_SNOWFLAKE_TEST_3:
    PUBLIC_3:
    - BANK_ACCOUNTS_3

source_id:
  snowflake_azure_central_us
